### ISSUE TITLE
Plugin runs successfully but output not showing style

### ISSUE THREAD

**Issue by navanchauhan** [Ze0nC/SwiftPygmentsPublishPlugin#1]
```swift
try MyWebsite().publish(
    
    withTheme: .alpha,
    
    additionalSteps: [.installPlugin(.pygments()), .deploy(using: .gitHub("navanchauhan/navanchauhan.github.io"))])
   
```
[index.txt](https://github.com/Ze0nC/SwiftPygmentsPublishPlugin/files/4080116/index.txt)

GitHub does not allow uploading HTML files, so I renamed it to txt, all code tags are correctly showing language-python 

```html
<code class="language-python">
```

I have only one additional css property for pre tag

```css
pre {
    overflow-x: auto;
    font-family: Monaco,Consolas,"Lucida Console",monospace;
    display: block;
    margin-bottom: 1em;
    background: #333;/*#263238;*/
    color: #eee; /*#eff;*/
    line-height: 1.8;
    border-radius: 4px;
}
```
After this follows the solarized-dark theme from mpchadwick/pygments-high-contrast

[theme-css]("https://raw.githubusercontent.com/mpchadwick/pygments-high-contrast-stylesheets/gh-pages/solarized-dark.css")
